### PR TITLE
Basic single page site with links pointing to various ReadMe files

### PR DESCRIPTION
**Pull request by walmik**
Demo: http://walmik.info/nemo/

### CODE REVIEW

**Comment by gkushang** [comment]
nice job @walmik :+1: This can be a good place to list all the available nemo plugins - cc @grawk - any thoughts?

**Comment by grawk** [comment]
Hi @walmik. I'm very sorry I didn't comment earlier. My initial concern is that some of the critical information is hidden when viewed on a mobile browser (i.e. how to clone the sample app).

**Comment by grawk** [comment]
Also, the information in the image regarding installation should be text such that it can be copied from the site and pasted into a terminal. We should modify the layout such that the example bash script is actually text and not an image.

**Comment by walmik** [comment]
@gkushang  @grawk Thanks for your comments! I ll make changes accordingly and update this PR.

**Comment by nikulkarni** [comment]
This looks really nice and much appealing than existing site. Great job @walmik! I agree that it needs highlight important content. It's also worth noting that nemojs is unopinionated as far as test frameworks are concerned.  It can work with mocha, jasmine, cucumberjs or any other frameworks. All that said I'm of an opinion that lets get the first version of pages merged and then make iterative improvements. Cool stuff!

**Comment by walmik** [comment]
Made changes as per comments. Added rudimentary support for mobile.

**Comment by walmik** [comment]
Squashed multiple commits into one

**Comment by grawk** [comment]
new website go!

**Pull request merged**
