### PR TITLE
Add package information to the capabilities in driver.

### PR DESCRIPTION
**Pull request by ILikeToNguyen**
Add package information to the capabilities in driver.
The added caps are
- teamname: grabbed from package.json name field
- description: grabbed from package.json description field
- name: testname is created by using a combination of the nemoBaseDir Or cwd + team name + an incremental counter

I was not able to get the mocha test name or path to the current mocha js file.  I created a question in the mocha github repo to see if others had any ideas.  There you can see what I tried or thought of.
https://github.com/mochajs/mocha/issues/2065

So for example, running the 4 tests from nemo-example-app looks like 
name : /Users/antnguyen/dev/repo/nemo-example-app/test/-nemo-example-app-1
name : /Users/antnguyen/dev/repo/nemo-example-app/test/-nemo-example-app-2
name : /Users/antnguyen/dev/repo/nemo-example-app/test/-nemo-example-app-3
name : /Users/antnguyen/dev/repo/nemo-example-app/test/-nemo-example-app-4

Custom capabilities should be set even if only builders are used instead
of specifying a tgtBrowser.

Decision to put this in nemo vs a plugin
We decided to do this directly in nemo where the driver's capabilities were being initialized as we felt these capabilities were core information that should be added during driver initialization.  There are various selenium servers that will utilize this information.
For example: 
-Saucelabs uses the capability field "name" for display in their test runs list.  Here is an example of what it looks like when the name capability isnt set.
https://saucelabs.com/users/cueTester/tests
-Selion has analytics that will capture the "name" field from capabilities and let you configure other capability fields for display.
-Groupon's Selenium-Grid-Extras utilizes the desiredCapabilites in their HtmlRenderer so having the teamName and testName in there would be useful.
 https://github.com/groupon/Selenium-Grid-Extras/blob/e4975cedc265100f36ffb492e4db3a6a1a3413bb/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/proxies/ExtrasHtmlRenderer.java

### CODE REVIEW

**Comment by grawk** [comment]
Looks like the CI build failed with some lint errors.

Hi @ILikeToNguyen 

It appears you are intending to add metadata to the properties in the mocha test execution case. Can you provide some more background on why you want to do this?

Also, can it be achieved in a pre-driver plugin instead? We don't want to put features that are too specific to a particular use case in the core module.

**Comment by ILikeToNguyen** [comment]
@grawk
Yes I need to address those lint errors.

The 4 capabilities I'm setting are not specifically tied to mocha.  They are information about the product being tested.  

"Can you provide some more background on why you want to do this?"
- My specific immediate use case is in our logstash analytics of the Grid, I can gather metrics on teams that are running selenium tests on our Grid.  Soon we will use this information to display metrics on our dockerized grid.
- A couple customers using saucelabs with nemo have requested that the name be automatically set just like SeLion because the table that shows the running tests displays the "name".  Its hard for them to drill into which tests are running/failing since they all have the same test name of "none".  Recently its been changed to display the browsername instead of none if "name" isnt specified.

pre-driver plugin:
Originally I started doing it as a pre-driver plugin but after some discussion locally here, we felt it was more of a core capability to have name be defined in the framework since it is a generic concept to set the information about the execution in the capability.  Do you think name and teamname are good capabilities to set for the user automatically from nemo's core for general reporting/analytics purposes?

**Comment by grawk** [comment]
I'm concerned that once we start throwing in these types of properties it will lead to more for different but similar use cases. My inclination is to ask this be made as a plugin. But let's talk a bit offline and summarize our discussion here afterwards @ILikeToNguyen

**Comment by ILikeToNguyen** [comment]
After discussion, a pre driver plugin will be created that will add the project information to the web session request's capabilities.

A separate PR will created that addresses the ability to have custom capabilities when using builders.

**Pull request closed without merging**
