### PR TITLE
Selenium 3

### PR DESCRIPTION
**Pull request by gkushang**
* Firefox requires a `geckodriver` to be in your PATH. 
* Deprecated promises have been removed from Selenium 3

TODO: 
* [nemo-docs](https://github.com/paypal/nemo-docs) needs an update for firefox driver
* [nemo-view](https://github.com/paypal/nemo-view) should be updated to support Selenium 3

### CODE REVIEW

**Comment by grawk** [comment]
Do we consider selenium3 support to be a breaking change?

**Comment by gkushang** [comment]
yes - I'd consider this as a breaking change due to change is `managed-promises` and also Firefox gets it's own web-driver.

**Comment by aredridel** [comment]
Yeah, if the promises exposed change then it'll have to be breaking I think. Unless it's fully backward compatible, but considering the surface area and number of edge cases in that, that's doubtful.

**Comment by nikulkarni** [comment]
I would say, lets hold on merging this until 3.0.0 is released

**Comment by gkushang** [comment]
I agree, it can part of nemo@3. Other `nemo` plugins need updates too, in order to process unhappy WD promises.

**Comment by grawk** [comment]
We should probably publish a v3 alpha in order to shake out other issues related to moving to selenium@3. Also, not sure what other things we might consider but maybe there are additional enhancements we'd like to put into nemo@3 along with selenium@3 support.

**Comment by grawk** [comment]
@gkushang I've created a branch `3.0-alpha` where we can start work for nemo@3. Please re-open this request there.

**Comment by gkushang** [comment]
That sounds great. Will reopen - I like that our versioning matches with Selenium versioning 😄

**Pull request closed without merging**
