### PR TITLE
assign config to nemo object

### PR DESCRIPTION
**Pull request by kugajjar**
Assign config to nemo object so that it is available along with nemo object.

### CODE REVIEW

**Comment by nikulkarni** [comment]
Hey @kugajjar looks like your fork is not updated with upstream develop and is up to date with upstream master. Although it seems that the badge is in master and missing in develop. The other unit test I see in this PR is not in master/develop anymore.

**Comment by kugajjar** [comment]
@nikulkarni I updated my develop with upstream, How does it look now?

**Comment by nikulkarni** [comment]
PR looks good, however, for some reason commit history still shows history in master. I don't know if this has any side effects though.

**Comment by grawk** [comment]
:+1:

**Comment by grawk** [comment]
@gkushang please let me know what email address i should use when adding you to the contributors block in package.json. Thanks.

**Comment by gkushang** [comment]
@grawk you can use ```g.kushang@gmail.com```

**Pull request merged**
