### PR TITLE
es6 changes

### PR DESCRIPTION
**Pull request by manoj9788**
@grawk as we discussed raising this PR for moving towards es6

### CODE REVIEW

**Comment by nikulkarni** [comment]
Cool, can you open this PR against develop?

**Comment by skratchdot** [comment]
lgtm except for the 4 places we are still using var (and the PR needs to be submitted to the `develop` branch).

**Comment by manoj9788** [comment]
Sure, I will raise this in develop branch. This PR needs to be closed here ?

**Comment by skratchdot** [comment]
Well, it looks like it let me switch the base to develop, but now there are merge conflicts.  So you can either close this out, or just do:

```
git checkout manoj-develop
git pull --rebase upstream develop
# fix merge conflicts
git push -f origin manoj-develop
```

I guess that's up to you!

**Comment by grawk** [comment]
would recommend closing this one and re-opening based on the recently merged refactor (breaking up the large index.js file into several lib/* files)

**Comment by skratchdot** [comment]
@manoj9788 - I'm going to go ahead and close this.  Just submit a new one when the rebase on develop is done.  Thanks for the work!

**Comment by manoj9788** [comment]
I have opened a new PR #159 with newly forked instance from origin develop

**Pull request closed without merging**
