### PR TITLE
Upgrading the selenium version

### PR DESCRIPTION
**Pull request by pmpranav**
1 ) Upgraded the selenium version to 2.46.1. 

2 ) Bumped the minor version 

3) Some code changes in the setup/index.js file to make sure the driver is returned only after the promise is resolved.

### CODE REVIEW

**Comment by aredridel** [comment]
Why does one have to wait for the driver?

And can one use the session promise instead of polling?

**Comment by pmpranav** [comment]
@aredridel  
1) There are some issues when using the latest webdriver versions with mocha. Mocha is not waiting for the session promise to get resolved to continue execution. When we are running the test cases this means a browser window is opened yet nothing happens. This is the reason why we made nemo wait for the session promise to be resolved, so that this problem doesn't arise.

2) You are right. Using the session promise is better that polling. Will change that.

In webdriver/testing folder they have a modified version of mocha, where they use control flow to accomplish this. But i thought this would be simpler.

**Comment by grawk** [comment]
Hi @pmpranav exactly what was "broken" by the previous callback mechanism? Is there a test case in nemo or anywhere else that actually had a problem? I'd like to see an illustration of the problem in the form of a test case before moving forward with a change to the callback mechanism.

**Comment by pmpranav** [comment]
Hi @grawk. Its not a problem with the nemo setup callback mechanism. We can get the same result by adding the same thing in the nemo/index.js file in this place also
https://github.com/paypal/nemo/blob/master/index.js#L203-L204

All we need to do is to make mocha wait for the driver, this is just a work around for that issue.

The problem arises when we use the latest versions of selenium with mocha.
I have created three testcases here
One uses selenium with out mocha and runs fine
https://github.com/pmpranav/selenium_mocha_examples/blob/master/raw_selenium.js 

This one does the same thing using mocha and fails 
https://github.com/pmpranav/selenium_mocha_examples/blob/master/selenium_with_mocha.js

This one uses the mocha wrappers provided in selenium-webdriver/testing instead of mocha
https://github.com/pmpranav/selenium_mocha_examples/blob/master/with_selenium_mocha_wrappers.js

They are using the control flow class to create these wrappers. Perhaps we can make use of something similar instead of this method

**Comment by grawk** [comment]
Hi @pmpranav I've taken your changes, and then added a getSession callback to replace the interval timer you added. The result is the same but using the driver.getSession promise appropriately utilizes the webdriver API.

**Pull request closed without merging**
