### PR TITLE
Now allowing consumer provided selenium version

### PR DESCRIPTION
**Pull request by nikulkarni**
- Now allowing consumer provided selenium version
- Also got rid off xunit-file

This PR takes care of https://github.com/paypal/nemo/issues/88 and https://github.com/paypal/nemo/issues/76

### CODE REVIEW

**Comment by grawk** [comment]
That's a very neat pattern!

In the event that I already have the installed version that I specify in `selenium.version`, I assume there will be no npm install.

**Comment by nikulkarni** [comment]
yeah, `forceInstall: false` takes care of it from options object.

var options = {
      name: 'selenium-webdriver',
      version: version,       
      path: '.',
      forceInstall: false,
      npmLoad: {
        loglevel: 'silent'
      }
    };

**Comment by grawk** [comment]
What do you think we should do in terms of a test/release/doc plan for this?

**Comment by nikulkarni** [comment]
I tested this locally and works fine. We can do an alpha release but I'm not in big favor of it. Its just on/off feature and can go fine with regular release. I'm not sure about the documentation? Perhaps we can add more like, if the selenium version used by nemo is incompatible with firefox (mostly) or any other browsers, users can override it by providing their own selenium version?

**Comment by nikulkarni** [comment]
Hey can we get this merged soon? This address two open issues.

**Comment by grawk** [comment]
Sorry for letting this sit for so long :(

Has this been tested in various operating systems? OS X/*nix/Windows?

**Comment by grawk** [comment]
Given, like you said, this is non-breaking, gonna go ahead and put it in a minor release.

**Pull request merged**
